version: '2'
services:
    bgx-app:
        image: bgx
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://bgx-mysql:3306/bgx?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=bgx-elasticsearch:9300
        ports:
            - 8080:8080
    bgx-mysql:
        extends:
            file: mysql.yml
            service: bgx-mysql
    bgx-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: bgx-elasticsearch
